// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrycohpkvfeuonzweeik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyeWNvaHBrdmZldW9uendlZWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTI1MDMsImV4cCI6MjA2MDM2ODUwM30.kWRDINsq8XU_Uv97KfMh_3T6NwIxI88_AMZ_JYF_ntc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);